### ISSUE TITLE
Error compiling py2nim.nim

### ISSUE THREAD

**Issue by wizzardx** [metacraft-labs/py2nim#12]
At this step in the tutorial:

```
nim c py2nim.nim
```

I'm getting this error:

```
tracer.nim(63, 24) Error: ambiguous call; both strformat.%(pattern: string)[declared in lib/pure/strformat.nim(229, 6)] and json.%(s: string)[declared in lib/pure/json.nim(753, 5)] match for: (string)
```

I'm running the latest version of nim devel (commit 430a6c481).

**Comment by Yardanico** [comment]
Change "import strformat" to "import strformat except %" in this file

**Comment by alehander42** [comment]
This should be fixed now

**Comment by Yardanico** [comment]
No, you don't need to remove fmt! You can keep it

**Comment by Yardanico** [comment]
With "except %" you import everything from strformat except % so you can still use fmt
