### ISSUE TITLE
Update project README

### ISSUE THREAD

**Issue by m4r35n357** [metacraft-labs/py2nim#22]
According to this page:
https://en.wikipedia.org/wiki/Nim_%28programming_language%29

py2nim is a tool used for transpiling Python code into idiomatic Nim code

The README refers to a binary that is not there, and the source does virtually nothing.

**Comment by zielmicha** [comment]
Isn't the binary here: https://github.com/metacraft-labs/languist ?

**Comment by m4r35n357** [comment]
The README does not say to look there.  I just had a quick look anyway and couldn't find it.
I have been talking on IRC #nim and was going to try some of their suggestions.

**Comment by m4r35n357** [comment]
Maybe change issue title to update README?  I judged the project dead after 10 months of inactivity.

**Comment by alehander92** [comment]
sorry, this was fixed after irc , thanks: yeah probably we can move the original old one here again and move the languist py2nim to .. python2nim or something, not really sure, so i prefer to make that decision if eventually we'll decide on continuing with languist or with simpler approach

**Comment by m4r35n357** [comment]
Cheers, still investigating BTW.
